using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Animations : MonoBehaviour
{
    Animator anim;
    public float velocidad = 0.0f;
    public float aceleraci贸n = 0.1f;
    public float desaceleraci贸n = 0.5f;
    public bool moverseoprimido;


    void Start()
    {
        
        anim = GetComponent<Animator>();
    }

    
    void Update()
    {
        bool moverseoprimido = Input.GetKey("w");

        if (moverseoprimido && velocidad < 1.0f)
        {
            velocidad += Time.deltaTime * aceleraci贸n;
        }

         if (!moverseoprimido && velocidad > 0.0)
        {
            velocidad -= Time.deltaTime * desaceleraci贸n;
        }
        if (!moverseoprimido && velocidad < 0.0f)
        {
            velocidad = 0.0f;
        }
        anim.SetFloat("Velocity", velocidad);
    }
}
